--1.CREATED TABLE, SET PRIMARY KEY AND LOADED DATA FROM CSV FILE AFTER DATA CLEANING 

CREATE OR REPLACE TABLE MG_SALES_DATA_FINAL
(
    ORDER_ID VARCHAR(25),
    ORDER_DATE DATE  PRIMARY KEY,
    SHIP_DATE DATE,
    SHIP_MODE VARCHAR(25),
    CUSTOMER_NAME VARCHAR(50),
    SEGMENT CHAR(15),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    MARKET CHAR(15),
    REGION CHAR(15),
    PRODUCT_ID VARCHAR(25) ,
    CATEGORY VARCHAR(25),
    SUB_CATEGORY VARCHAR(25),
    PRODUCT_NAME VARCHAR(200),
    SALES NUMBER (10,2),
    QUANTITY INT,
    DISCOUNT NUMBER(10,2),
    PROFIT NUMBER (10,5),
    SHIPPING_COST NUMBER(10,2),
    ORDER_PRIORITY VARCHAR(15),
    YEAR INT 
);

--2.DATA TYPE FOR ORDER_DATE & SHIP_DATE SHOULD BE "DATE" . 
--CHANGED THE FORMAT AND TYPE  IN CSV TO "YYYY-MM-DD"

--3.CHANGING PRIMARY KEY FROM ORDER_DATE TO ORDER_ID

ALTER TABLE MG_SALES_DATA_FINAL
DROP PRIMARY KEY;
ALTER TABLE MG_SALES_DATA_FINAL ADD  PRIMARY KEY (ORDER_ID);
DESCRIBE TABLE MG_SALES_DATA_FINAL;


--4.EXTACT THE LAST NUMBER AFTER THE - AND CREATE OTHER COLUMN AND UPDATE IT

SELECT ORDER_ID , SUBSTRING(ORDER_ID,9) AS ORDER_EXTRACT  FROM MG_SALES_DATA_FINAL;



--5.IF DISCOUNT IS GREATER THEN 0 THEN  YES ELSE FALSE

SELECT ORDER_ID , DISCOUNT ,
CASE 
    WHEN DISCOUNT > 0 THEN 'YES'
    ELSE 'FALSE'
END AS DISCOUNT_FLAG
FROM MG_SALES_DATA_FINAL;



--6.DAYS TAKEN FOR EACH ORDER TO PROCESS FOR THE SHIPMENT 

SELECT ORDER_ID , ORDER_DATE, SHIP_DATE ,DATEDIFF(DAY,ORDER_DATE,SHIP_DATE ) AS PROCESS_DAYS FROM MG_SALES_DATA_FINAL ; 

--7.RATINGS BASED ON PROCESS DAYS

SELECT ORDER_ID , ORDER_DATE, SHIP_DATE,
CASE 
    WHEN DATEDIFF(DAY,ORDER_DATE,SHIP_DATE) <= 3 THEN '5' 
    WHEN DATEDIFF(DAY,ORDER_DATE,SHIP_DATE) BETWEEN 4 AND 6   THEN '4' 
    WHEN DATEDIFF(DAY,ORDER_DATE,SHIP_DATE) BETWEEN 7 AND 10  THEN '3' 
    ELSE '2'
END AS RATINGS
FROM MG_SALES_DATA_FINAL;

